import React from "react";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return (
    <div className="flex flex-1 flex-col py-10">
      <Navbar />
      {children}
      <Footer />
    </div>
  );
}
